
import { JapaneseChar, GrammarPoint } from './types';

export const HIRAGANA: JapaneseChar[] = [
  // Basics
  { id: 'h1', char: 'あ', romaji: 'a', type: 'hiragana' },
  { id: 'h2', char: 'い', romaji: 'i', type: 'hiragana' },
  { id: 'h3', char: 'う', romaji: 'u', type: 'hiragana' },
  { id: 'h4', char: 'え', romaji: 'e', type: 'hiragana' },
  { id: 'h5', char: 'お', romaji: 'o', type: 'hiragana' },
  { id: 'h6', char: 'か', romaji: 'ka', type: 'hiragana' },
  { id: 'h7', char: 'き', romaji: 'ki', type: 'hiragana' },
  { id: 'h8', char: 'く', romaji: 'ku', type: 'hiragana' },
  { id: 'h9', char: 'け', romaji: 'ke', type: 'hiragana' },
  { id: 'h10', char: 'こ', romaji: 'ko', type: 'hiragana' },
  { id: 'h11', char: 'さ', romaji: 'sa', type: 'hiragana' },
  { id: 'h12', char: 'し', romaji: 'shi', type: 'hiragana' },
  { id: 'h13', char: 'す', romaji: 'su', type: 'hiragana' },
  { id: 'h14', char: 'せ', romaji: 'se', type: 'hiragana' },
  { id: 'h15', char: 'そ', romaji: 'so', type: 'hiragana' },
  { id: 'h16', char: 'た', romaji: 'ta', type: 'hiragana' },
  { id: 'h17', char: 'ち', romaji: 'chi', type: 'hiragana' },
  { id: 'h18', char: 'つ', romaji: 'tsu', type: 'hiragana' },
  { id: 'h19', char: 'て', romaji: 'te', type: 'hiragana' },
  { id: 'h20', char: 'と', romaji: 'to', type: 'hiragana' },
  { id: 'h21', char: 'な', romaji: 'na', type: 'hiragana' },
  { id: 'h22', char: 'に', romaji: 'ni', type: 'hiragana' },
  { id: 'h23', char: 'ぬ', romaji: 'nu', type: 'hiragana' },
  { id: 'h24', char: 'ね', romaji: 'ne', type: 'hiragana' },
  { id: 'h25', char: 'の', romaji: 'no', type: 'hiragana' },
  { id: 'h26', char: 'は', romaji: 'ha', type: 'hiragana' },
  { id: 'h27', char: 'ひ', romaji: 'hi', type: 'hiragana' },
  { id: 'h28', char: 'ふ', romaji: 'fu', type: 'hiragana' },
  { id: 'h29', char: 'へ', romaji: 'he', type: 'hiragana' },
  { id: 'h30', char: 'ほ', romaji: 'ho', type: 'hiragana' },
  { id: 'h31', char: 'ま', romaji: 'ma', type: 'hiragana' },
  { id: 'h32', char: 'み', romaji: 'mi', type: 'hiragana' },
  { id: 'h33', char: 'む', romaji: 'mu', type: 'hiragana' },
  { id: 'h34', char: 'め', romaji: 'me', type: 'hiragana' },
  { id: 'h35', char: 'も', romaji: 'mo', type: 'hiragana' },
  { id: 'h36', char: 'や', romaji: 'ya', type: 'hiragana' },
  { id: 'h37', char: 'ゆ', romaji: 'yu', type: 'hiragana' },
  { id: 'h38', char: 'よ', romaji: 'yo', type: 'hiragana' },
  { id: 'h39', char: 'ら', romaji: 'ra', type: 'hiragana' },
  { id: 'h40', char: 'り', romaji: 'ri', type: 'hiragana' },
  { id: 'h41', char: 'る', romaji: 'ru', type: 'hiragana' },
  { id: 'h42', char: 'れ', romaji: 're', type: 'hiragana' },
  { id: 'h43', char: 'ろ', romaji: 'ro', type: 'hiragana' },
  { id: 'h44', char: 'わ', romaji: 'wa', type: 'hiragana' },
  { id: 'h45', char: 'を', romaji: 'wo', type: 'hiragana' },
  { id: 'h46', char: 'ん', romaji: 'n', type: 'hiragana' },
  // Dakuten (k -> g)
  { id: 'h47', char: 'が', romaji: 'ga', type: 'hiragana' },
  { id: 'h48', char: 'ぎ', romaji: 'gi', type: 'hiragana' },
  { id: 'h49', char: 'ぐ', romaji: 'gu', type: 'hiragana' },
  { id: 'h50', char: 'げ', romaji: 'ge', type: 'hiragana' },
  { id: 'h51', char: 'ご', romaji: 'go', type: 'hiragana' },
  // Dakuten (s -> z)
  { id: 'h52', char: 'ざ', romaji: 'za', type: 'hiragana' },
  { id: 'h53', char: 'じ', romaji: 'ji', type: 'hiragana' },
  { id: 'h54', char: 'ず', romaji: 'zu', type: 'hiragana' },
  { id: 'h55', char: 'ぜ', romaji: 'ze', type: 'hiragana' },
  { id: 'h56', char: 'ぞ', romaji: 'zo', type: 'hiragana' },
  // Dakuten (t -> d)
  { id: 'h57', char: 'だ', romaji: 'da', type: 'hiragana' },
  { id: 'h58', char: 'ぢ', romaji: 'ji', type: 'hiragana' },
  { id: 'h59', char: 'づ', romaji: 'zu', type: 'hiragana' },
  { id: 'h60', char: 'で', romaji: 'de', type: 'hiragana' },
  { id: 'h61', char: 'ど', romaji: 'do', type: 'hiragana' },
  // Dakuten (h -> b)
  { id: 'h62', char: 'ば', romaji: 'ba', type: 'hiragana' },
  { id: 'h63', char: 'び', romaji: 'bi', type: 'hiragana' },
  { id: 'h64', char: 'ぶ', romaji: 'bu', type: 'hiragana' },
  { id: 'h65', char: 'べ', romaji: 'be', type: 'hiragana' },
  { id: 'h66', char: 'ぼ', romaji: 'bo', type: 'hiragana' },
  // Handakuten (h -> p)
  { id: 'h67', char: 'ぱ', romaji: 'pa', type: 'hiragana' },
  { id: 'h68', char: 'ぴ', romaji: 'pi', type: 'hiragana' },
  { id: 'h69', char: 'ぷ', romaji: 'pu', type: 'hiragana' },
  { id: 'h70', char: 'ぺ', romaji: 'pe', type: 'hiragana' },
  { id: 'h71', char: 'ぽ', romaji: 'po', type: 'hiragana' },
];

export const KATAKANA: JapaneseChar[] = [
  { id: 'k1', char: 'ア', romaji: 'a', type: 'katakana' },
  { id: 'k2', char: 'イ', romaji: 'i', type: 'katakana' },
  { id: 'k3', char: 'ウ', romaji: 'u', type: 'katakana' },
  { id: 'k4', char: 'エ', romaji: 'e', type: 'katakana' },
  { id: 'k5', char: 'オ', romaji: 'o', type: 'katakana' },
  { id: 'k6', char: 'カ', romaji: 'ka', type: 'katakana' },
  { id: 'k7', char: 'キ', romaji: 'ki', type: 'katakana' },
  { id: 'k8', char: 'ク', romaji: 'ku', type: 'katakana' },
  { id: 'k9', char: 'ケ', romaji: 'ke', type: 'katakana' },
  { id: 'k10', char: 'コ', romaji: 'ko', type: 'katakana' },
  { id: 'k11', char: 'サ', romaji: 'sa', type: 'katakana' },
  { id: 'k12', char: 'シ', romaji: 'shi', type: 'katakana' },
  { id: 'k13', char: 'ス', romaji: 'su', type: 'katakana' },
  { id: 'k14', char: 'セ', romaji: 'se', type: 'katakana' },
  { id: 'k15', char: 'ソ', romaji: 'so', type: 'katakana' },
  { id: 'k16', char: 'タ', romaji: 'ta', type: 'katakana' },
  { id: 'k17', char: 'チ', romaji: 'chi', type: 'katakana' },
  { id: 'k18', char: 'ツ', romaji: 'tsu', type: 'katakana' },
  { id: 'k19', char: 'テ', romaji: 'te', type: 'katakana' },
  { id: 'k20', char: 'ト', romaji: 'to', type: 'katakana' },
  { id: 'k21', char: 'ナ', romaji: 'na', type: 'katakana' },
  { id: 'k22', char: 'ニ', romaji: 'ni', type: 'katakana' },
  { id: 'k23', char: 'ヌ', romaji: 'nu', type: 'katakana' },
  { id: 'k24', char: 'ネ', romaji: 'ne', type: 'katakana' },
  { id: 'k25', char: 'ノ', romaji: 'no', type: 'katakana' },
  { id: 'k26', char: 'ハ', romaji: 'ha', type: 'katakana' },
  { id: 'k27', char: 'ヒ', romaji: 'hi', type: 'katakana' },
  { id: 'k28', char: 'フ', romaji: 'fu', type: 'katakana' },
  { id: 'k29', char: 'ヘ', romaji: 'he', type: 'katakana' },
  { id: 'k30', char: 'ホ', romaji: 'ho', type: 'katakana' },
  { id: 'k31', char: 'マ', romaji: 'ma', type: 'katakana' },
  { id: 'k32', char: 'ミ', romaji: 'mi', type: 'katakana' },
  { id: 'k33', char: 'ム', romaji: 'mu', type: 'katakana' },
  { id: 'k34', char: 'メ', romaji: 'me', type: 'katakana' },
  { id: 'k35', char: 'モ', romaji: 'mo', type: 'katakana' },
  { id: 'k36', char: 'ヤ', romaji: 'ya', type: 'katakana' },
  { id: 'k37', char: 'ユ', romaji: 'yu', type: 'katakana' },
  { id: 'k38', char: 'ヨ', romaji: 'yo', type: 'katakana' },
  { id: 'k39', char: 'ラ', romaji: 'ra', type: 'katakana' },
  { id: 'k40', char: 'リ', romaji: 'ri', type: 'katakana' },
  { id: 'k41', char: 'ル', romaji: 'ru', type: 'katakana' },
  { id: 'k42', char: 'レ', romaji: 're', type: 'katakana' },
  { id: 'k43', char: 'ロ', romaji: 'ro', type: 'katakana' },
  { id: 'k44', char: 'ワ', romaji: 'wa', type: 'katakana' },
  { id: 'k45', char: 'ヲ', romaji: 'wo', type: 'katakana' },
  { id: 'k46', char: 'ン', romaji: 'n', type: 'katakana' },
];

export const KANJI_N5: JapaneseChar[] = [
  { id: 'kn1', char: '一', romaji: 'ichi', meaning: 'One', sinoVietnamese: 'Nhất', onyomi: 'イチ', kunyomi: 'ひと', exampleVocab: '一人 (hitori - one person)', type: 'kanji' },
  { id: 'kn2', char: '二', romaji: 'ni', meaning: 'Two', sinoVietnamese: 'Nhị', onyomi: 'ニ', kunyomi: 'ふた', exampleVocab: '二日 (futsuka - second day)', type: 'kanji' },
  { id: 'kn3', char: '三', romaji: 'san', meaning: 'Three', sinoVietnamese: 'Tam', onyomi: 'サン', kunyomi: 'み', exampleVocab: '三日 (mikka - third day)', type: 'kanji' },
  { id: 'kn4', char: '四', romaji: 'yon', meaning: 'Four', sinoVietnamese: 'Tứ', onyomi: 'シ', kunyomi: 'よ', exampleVocab: '四日 (yokka - fourth day)', type: 'kanji' },
  { id: 'kn5', char: '五', romaji: 'go', meaning: 'Five', sinoVietnamese: 'Ngũ', onyomi: 'ゴ', kunyomi: 'いつ', exampleVocab: '五日 (itsuka - fifth day)', type: 'kanji' },
  { id: 'kn6', char: '六', romaji: 'roku', meaning: 'Six', sinoVietnamese: 'Lục', onyomi: 'ロク', kunyomi: 'む', exampleVocab: '六日 (muika - sixth day)', type: 'kanji' },
  { id: 'kn7', char: '七', romaji: 'nana', meaning: 'Seven', sinoVietnamese: 'Thất', onyomi: 'シチ', kunyomi: 'なな', exampleVocab: '七日 (nanoka - seventh day)', type: 'kanji' },
  { id: 'kn8', char: '八', romaji: 'hachi', meaning: 'Eight', sinoVietnamese: 'Bát', onyomi: 'ハチ', kunyomi: 'や', exampleVocab: '八日 (youka - eighth day)', type: 'kanji' },
  { id: 'kn9', char: '九', romaji: 'kyuu', meaning: 'Nine', sinoVietnamese: 'Cửu', onyomi: 'キュウ', kunyomi: 'ここの', exampleVocab: '九日 (kokonoka - ninth day)', type: 'kanji' },
  { id: 'kn10', char: '十', romaji: 'juu', meaning: 'Ten', sinoVietnamese: 'Thập', onyomi: 'ジュウ', kunyomi: 'とお', exampleVocab: '十日 (tooka - tenth day)', type: 'kanji' },
  { id: 'kn11', char: '百', romaji: 'hyaku', meaning: 'Hundred', sinoVietnamese: 'Bách', onyomi: 'ヒャク', kunyomi: '—', exampleVocab: '三百 (san-byaku - three hundred)', type: 'kanji' },
  { id: 'kn12', char: '千', romaji: 'sen', meaning: 'Thousand', sinoVietnamese: 'Thiên', onyomi: 'セン', kunyomi: 'ち', exampleVocab: '三千 (san-zen - three thousand)', type: 'kanji' },
  { id: 'kn13', char: '万', romaji: 'man', meaning: 'Ten Thousand', sinoVietnamese: 'Vạn', onyomi: 'マン', kunyomi: '—', exampleVocab: '一万円 (ichi-man-en - 10,000 yen)', type: 'kanji' },
  { id: 'kn14', char: '円', romaji: 'en', meaning: 'Yen / Circle', sinoVietnamese: 'Viên', onyomi: 'エン', kunyomi: 'まる', exampleVocab: '円い (marui - round)', type: 'kanji' },
  { id: 'kn15', char: '日', romaji: 'nichi', meaning: 'Day / Sun', sinoVietnamese: 'Nhật', onyomi: 'ニチ / ジツ', kunyomi: 'ひ', exampleVocab: '休日 (kyuujitsu - holiday)', type: 'kanji' },
  { id: 'kn16', char: '月', romaji: 'getsu', meaning: 'Month / Moon', sinoVietnamese: 'Nguyệt', onyomi: 'ゲツ / ガツ', kunyomi: 'つき', exampleVocab: '今月 (kongetsu - this month)', type: 'kanji' },
  { id: 'kn17', char: '火', romaji: 'ka', meaning: 'Fire', sinoVietnamese: 'Hỏa', onyomi: 'カ', kunyomi: 'ひ', exampleVocab: '火曜日 (kayoubi - Tuesday)', type: 'kanji' },
  { id: 'kn18', char: '水', romaji: 'sui', meaning: 'Water', sinoVietnamese: 'Thủy', onyomi: 'スイ', kunyomi: 'みず', exampleVocab: '水泳 (suiei - swimming)', type: 'kanji' },
  { id: 'kn19', char: '木', romaji: 'moku', meaning: 'Tree', sinoVietnamese: 'Mộc', onyomi: 'モク', kunyomi: 'き', exampleVocab: '木曜日 (mokuyoubi - Thursday)', type: 'kanji' },
  { id: 'kn20', char: '金', romaji: 'kin', meaning: 'Gold / Money', sinoVietnamese: 'Kim', onyomi: 'キン', kunyomi: 'かね', exampleVocab: 'お金 (okane - money)', type: 'kanji' },
  { id: 'kn21', char: '土', romaji: 'do', meaning: 'Earth / Soil', sinoVietnamese: 'Thổ', onyomi: 'ド', kunyomi: 'つち', exampleVocab: '土曜日 (doyoubi - Saturday)', type: 'kanji' },
  { id: 'kn22', char: '山', romaji: 'yama', meaning: 'Mountain', sinoVietnamese: 'Sơn', onyomi: 'サン', kunyomi: 'やま', exampleVocab: '富士山 (fujisan - Mt Fuji)', type: 'kanji' },
  { id: 'kn23', char: '川', romaji: 'kawa', meaning: 'River', sinoVietnamese: 'Xuyên', onyomi: 'セン', kunyomi: 'かわ', exampleVocab: '小川 (ogawa - brook)', type: 'kanji' },
  { id: 'kn24', char: '田', romaji: 'ta', meaning: 'Rice field', sinoVietnamese: 'Điền', onyomi: 'デン', kunyomi: 'た', exampleVocab: '田んぼ (tanbo - rice field)', type: 'kanji' },
  { id: 'kn25', char: '人', romaji: 'hito', meaning: 'Person', sinoVietnamese: 'Nhân', onyomi: 'ジン / ニン', kunyomi: 'ひと', exampleVocab: '日本人 (nihonjin - Japanese person)', type: 'kanji' },
  { id: 'kn26', char: '子', romaji: 'ko', meaning: 'Child', sinoVietnamese: 'Tử', onyomi: 'シ', kunyomi: 'こ', exampleVocab: '女の子 (onnanoko - girl)', type: 'kanji' },
  { id: 'kn27', char: '女', romaji: 'onna', meaning: 'Woman', sinoVietnamese: 'Nữ', onyomi: 'ジョ', kunyomi: 'おんな', exampleVocab: '彼女 (kanojo - girlfriend)', type: 'kanji' },
  { id: 'kn28', char: '男', romaji: 'otoko', meaning: 'Man', sinoVietnamese: 'Nam', onyomi: 'ダン', kunyomi: 'おとこ', exampleVocab: '長男 (chounan - eldest son)', type: 'kanji' },
  { id: 'kn29', char: '父', romaji: 'chichi', meaning: 'Father', sinoVietnamese: 'Phụ', onyomi: 'フ', kunyomi: 'ちち', exampleVocab: 'お父さん (otousan - father)', type: 'kanji' },
  { id: 'kn30', char: '母', romaji: 'haha', meaning: 'Mother', sinoVietnamese: 'Mẫu', onyomi: 'ボ', kunyomi: 'はは', exampleVocab: 'お母さん (okaasan - mother)', type: 'kanji' },
  { id: 'kn31', char: '友', romaji: 'tomo', meaning: 'Friend', sinoVietnamese: 'Hữu', onyomi: 'ユウ', kunyomi: 'とも', exampleVocab: '友達 (tomodachi - friend)', type: 'kanji' },
  { id: 'kn32', char: '本', romaji: 'hon', meaning: 'Book / Origin', sinoVietnamese: 'Bản', onyomi: 'ホン', kunyomi: 'もと', exampleVocab: '日本 (nihon - Japan)', type: 'kanji' },
  { id: 'kn33', char: '学', romaji: 'gaku', meaning: 'Study', sinoVietnamese: 'Học', onyomi: 'ガク', kunyomi: 'まなぶ', exampleVocab: '学生 (gakusei - student)', type: 'kanji' },
  { id: 'kn34', char: '生', romaji: 'sei', meaning: 'Life / Birth', sinoVietnamese: 'Sinh', onyomi: 'セイ / ショウ', kunyomi: 'いきる', exampleVocab: '先生 (sensei - teacher)', type: 'kanji' },
  { id: 'kn35', char: '先', romaji: 'saki', meaning: 'Ahead / Previous', sinoVietnamese: 'Tiên', onyomi: 'セン', kunyomi: 'さき', exampleVocab: '先月 (sengetsu - last month)', type: 'kanji' },
  { id: 'kn36', char: '何', romaji: 'nani', meaning: 'What', sinoVietnamese: 'Hà', onyomi: 'カ', kunyomi: 'なに', exampleVocab: '何人 (naninin - how many people)', type: 'kanji' },
  { id: 'kn37', char: '私', romaji: 'watashi', meaning: 'I / Me', sinoVietnamese: 'Tư', onyomi: 'シ', kunyomi: 'わたし', exampleVocab: '私立 (shiritsu - private)', type: 'kanji' },
  { id: 'kn38', char: '毎', romaji: 'mai', meaning: 'Every', sinoVietnamese: 'Mỗi', onyomi: 'マイ', kunyomi: '—', exampleVocab: '毎日 (mainichi - every day)', type: 'kanji' },
  { id: 'kn39', char: '年', romaji: 'toshi', meaning: 'Year', sinoVietnamese: 'Niên', onyomi: 'ネン', kunyomi: 'とし', exampleVocab: '去年 (kyonen - last year)', type: 'kanji' },
  { id: 'kn40', char: '時', romaji: 'toki', meaning: 'Time / Hour', sinoVietnamese: 'Thời', onyomi: 'ジ', kunyomi: 'とき', exampleVocab: '時計 (tokei - watch)', type: 'kanji' },
  { id: 'kn41', char: '分', romaji: 'fun', meaning: 'Minute / Part', sinoVietnamese: 'Phân', onyomi: 'ブン / プン', kunyomi: 'わける', exampleVocab: '半分 (hanbun - half)', type: 'kanji' },
  { id: 'kn42', char: '前', romaji: 'mae', meaning: 'Before / Front', sinoVietnamese: 'Tiền', onyomi: 'ゼン', kunyomi: 'まえ', exampleVocab: '名前 (namae - name)', type: 'kanji' },
  { id: 'kn43', char: '後', romaji: 'ato', meaning: 'After / Behind', sinoVietnamese: 'Hậu', onyomi: 'ゴ', kunyomi: 'うしろ', exampleVocab: '後ろ (ushiro - behind)', type: 'kanji' },
  { id: 'kn44', char: '午', romaji: 'go', meaning: 'Noon', sinoVietnamese: 'Ngọ', onyomi: 'ゴ', kunyomi: '—', exampleVocab: '午前 (gozen - morning)', type: 'kanji' },
  { id: 'kn45', char: '今', romaji: 'ima', meaning: 'Now', sinoVietnamese: 'Kim', onyomi: 'コン', kunyomi: 'いま', exampleVocab: '今日 (kyou - today)', type: 'kanji' },
  { id: 'kn46', char: '休', romaji: 'yasu', meaning: 'Rest', sinoVietnamese: 'Hưu', onyomi: 'キュウ', kunyomi: 'やすむ', exampleVocab: '休み (yasumi - holiday)', type: 'kanji' },
  { id: 'kn47', char: '語', romaji: 'go', meaning: 'Language', sinoVietnamese: 'Ngữ', onyomi: 'ゴ', kunyomi: 'かたる', exampleVocab: '日本語 (nihongo - Japanese)', type: 'kanji' },
  { id: 'kn48', char: '天', romaji: 'ten', meaning: 'Heaven / Sky', sinoVietnamese: 'Thiên', onyomi: 'テン', kunyomi: 'あめ', exampleVocab: '天気 (tenki - weather)', type: 'kanji' },
  { id: 'kn49', char: '気', romaji: 'ki', meaning: 'Spirit / Air', sinoVietnamese: 'Khí', onyomi: 'キ', kunyomi: '—', exampleVocab: '気持ち (kimochi - feeling)', type: 'kanji' },
  { id: 'kn50', char: '空', romaji: 'sora', meaning: 'Sky / Empty', sinoVietnamese: 'Không', onyomi: 'クウ', kunyomi: 'そら', exampleVocab: '空港 (kuukou - airport)', type: 'kanji' },
  { id: 'kn51', char: '雨', romaji: 'ame', meaning: 'Rain', sinoVietnamese: 'Vũ', onyomi: 'ウ', kunyomi: 'あめ', exampleVocab: '大雨 (ooame - heavy rain)', type: 'kanji' },
  { id: 'kn52', char: '電', romaji: 'den', meaning: 'Electricity', sinoVietnamese: 'Điện', onyomi: 'デン', kunyomi: '—', exampleVocab: '電車 (densha - train)', type: 'kanji' },
  { id: 'kn53', char: '車', romaji: 'kuruma', meaning: 'Car / Vehicle', sinoVietnamese: 'Xa', onyomi: 'シャ', kunyomi: 'くるま', exampleVocab: '自転車 (jitensha - bicycle)', type: 'kanji' },
  { id: 'kn54', char: '駅', romaji: 'eki', meaning: 'Station', sinoVietnamese: 'Trạm', onyomi: 'エキ', kunyomi: '—', exampleVocab: '東京駅 (toukyou-eki - Tokyo station)', type: 'kanji' },
  { id: 'kn55', char: '校', romaji: 'kou', meaning: 'School', sinoVietnamese: 'Hiệu', onyomi: 'コウ', kunyomi: '—', exampleVocab: '小学校 (shougakkou - primary school)', type: 'kanji' },
  { id: 'kn56', char: '店', romaji: 'mise', meaning: 'Shop', sinoVietnamese: 'Điếm', onyomi: 'テン', kunyomi: 'みせ', exampleVocab: '喫茶店 (kissaten - cafe)', type: 'kanji' },
  { id: 'kn57', char: '社', romaji: 'sha', meaning: 'Company / Shrine', sinoVietnamese: 'Xã', onyomi: 'シャ', kunyomi: 'やしろ', exampleVocab: '会社 (kaisha - company)', type: 'kanji' },
  { id: 'kn58', char: '国', romaji: 'kuni', meaning: 'Country', sinoVietnamese: 'Quốc', onyomi: 'コク', kunyomi: 'くに', exampleVocab: '外国 (gaikoku - foreign country)', type: 'kanji' },
  { id: 'kn59', char: '家', romaji: 'ie', meaning: 'House', sinoVietnamese: 'Gia', onyomi: 'カ', kunyomi: 'いえ', exampleVocab: '家族 (kazoku - family)', type: 'kanji' },
  { id: 'kn60', char: '上', romaji: 'ue', meaning: 'Above / Up', sinoVietnamese: 'Thượng', onyomi: 'ジョウ', kunyomi: 'うえ', exampleVocab: '上手 (jouzu - skillful)', type: 'kanji' },
  { id: 'kn61', char: '下', romaji: 'shita', meaning: 'Below / Down', sinoVietnamese: 'Hạ', onyomi: 'ゲ', kunyomi: 'した', exampleVocab: '地下鉄 (chikatetsu - subway)', type: 'kanji' },
  { id: 'kn62', char: '左', romaji: 'hidari', meaning: 'Left', sinoVietnamese: 'Tả', onyomi: 'サ', kunyomi: 'ひだり', exampleVocab: '左側 (hidarigawa - left side)', type: 'kanji' },
  { id: 'kn63', char: '右', romaji: 'migi', meaning: 'Right', sinoVietnamese: 'Hữu', onyomi: 'ユウ', kunyomi: 'みぎ', exampleVocab: '右利き (migikiki - right handed)', type: 'kanji' },
  { id: 'kn64', char: '中', romaji: 'naka', meaning: 'Middle / Inside', sinoVietnamese: 'Trung', onyomi: 'チュウ', kunyomi: 'なか', exampleVocab: '中国 (chuugoku - China)', type: 'kanji' },
  { id: 'kn65', char: '大', romaji: 'dai', meaning: 'Big', sinoVietnamese: 'Đại', onyomi: 'ダイ', kunyomi: 'おお', exampleVocab: '大学 (daigaku - university)', type: 'kanji' },
  { id: 'kn66', char: '小', romaji: 'shou', meaning: 'Small', sinoVietnamese: 'Tiểu', onyomi: 'ショウ', kunyomi: 'ちい', exampleVocab: '小学生 (shougakusei - elementary student)', type: 'kanji' },
  { id: 'kn67', char: '長', romaji: 'nagai', meaning: 'Long / Leader', sinoVietnamese: 'Trường', onyomi: 'チョウ', kunyomi: 'なが', exampleVocab: '社長 (shachou - president of company)', type: 'kanji' },
  { id: 'kn68', char: '高', romaji: 'takai', meaning: 'High / Expensive', sinoVietnamese: 'Cao', onyomi: 'コウ', kunyomi: 'たか', exampleVocab: '高校 (koukou - high school)', type: 'kanji' },
  { id: 'kn69', char: '安', romaji: 'yasui', meaning: 'Cheap / Safe', sinoVietnamese: 'An', onyomi: 'アン', kunyomi: 'やす', exampleVocab: '安心 (anshin - peace of mind)', type: 'kanji' },
  { id: 'kn70', char: '多', romaji: 'ooi', meaning: 'Many', sinoVietnamese: 'Đa', onyomi: 'タ', kunyomi: 'おお', exampleVocab: '多分 (tabun - probably)', type: 'kanji' },
  { id: 'kn71', char: '少', romaji: 'sukunai', meaning: 'Few / Little', sinoVietnamese: 'Thiểu', onyomi: 'ショウ', kunyomi: 'すく', exampleVocab: '少し (sukoshi - a little)', type: 'kanji' },
  { id: 'kn72', char: '新', romaji: 'atarashii', meaning: 'New', sinoVietnamese: 'Tân', onyomi: 'シン', kunyomi: 'あたら', exampleVocab: '新聞 (shinbun - newspaper)', type: 'kanji' },
  { id: 'kn73', char: '古', romaji: 'furui', meaning: 'Old', sinoVietnamese: 'Cổ', onyomi: 'コ', kunyomi: 'ふる', exampleVocab: '中古 (chuuko - second-hand)', type: 'kanji' },
  { id: 'kn74', char: '行', romaji: 'iku', meaning: 'To go', sinoVietnamese: 'Hành', onyomi: 'コウ', kunyomi: 'い', exampleVocab: '旅行 (ryokou - travel)', type: 'kanji' },
  { id: 'kn75', char: '来', romaji: 'kuru', meaning: 'To come', sinoVietnamese: 'Lai', onyomi: 'ライ', kunyomi: 'く', exampleVocab: '来年 (rainen - next year)', type: 'kanji' },
  { id: 'kn76', char: '食', romaji: 'taberu', meaning: 'To eat', sinoVietnamese: 'Thực', onyomi: 'ショク', kunyomi: 'た', exampleVocab: '食べ物 (tabemono - food)', type: 'kanji' },
  { id: 'kn77', char: '飲', romaji: 'nomu', meaning: 'To drink', sinoVietnamese: 'Ẩm', onyomi: 'イン', kunyomi: 'の', exampleVocab: '飲み物 (nomimono - drink)', type: 'kanji' },
  { id: 'kn78', char: '見', romaji: 'miru', meaning: 'To see', sinoVietnamese: 'Kiến', onyomi: 'ケン', kunyomi: 'み', exampleVocab: '見学 (kengaku - study trip)', type: 'kanji' },
  { id: 'kn79', char: '聞', romaji: 'kiku', meaning: 'To hear / listen', sinoVietnamese: 'Văn', onyomi: 'ブン', kunyomi: 'き', exampleVocab: '新聞 (shinbun - newspaper)', type: 'kanji' },
  { id: 'kn80', char: '書', romaji: 'kaku', meaning: 'To write', sinoVietnamese: 'Thư', onyomi: 'ショ', kunyomi: 'か', exampleVocab: '教科書 (kyoukasho - textbook)', type: 'kanji' },
  { id: 'kn81', char: '読', romaji: 'yomu', meaning: 'To read', sinoVietnamese: 'Độc', onyomi: 'ドク', kunyomi: 'よ', exampleVocab: '読書 (dokusho - reading)', type: 'kanji' },
  { id: 'kn82', char: '話', romaji: 'hanasu', meaning: 'To speak', sinoVietnamese: 'Thoại', onyomi: 'ワ', kunyomi: 'はな', exampleVocab: '会話 (kaiwa - conversation)', type: 'kanji' },
  { id: 'kn83', char: '買', romaji: 'kau', meaning: 'To buy', sinoVietnamese: 'Mãi', onyomi: 'バイ', kunyomi: 'か', exampleVocab: '買い物 (kaimono - shopping)', type: 'kanji' },
  { id: 'kn84', char: '入', romaji: 'hairu', meaning: 'To enter', sinoVietnamese: 'Nhập', onyomi: 'ニュウ', kunyomi: 'はい', exampleVocab: '入口 (iriguchi - entrance)', type: 'kanji' },
  { id: 'kn85', char: '出', romaji: 'deru', meaning: 'To exit', sinoVietnamese: 'Xuất', onyomi: 'シュツ', kunyomi: 'で', exampleVocab: '出口 (deguchi - exit)', type: 'kanji' },
  { id: 'kn86', char: '立', romaji: 'tatsu', meaning: 'To stand', sinoVietnamese: 'Lập', onyomi: 'リツ', kunyomi: 'た', exampleVocab: '国立 (kokuritsu - national)', type: 'kanji' },
  { id: 'kn87', char: '走', romaji: 'hashiru', meaning: 'To run', sinoVietnamese: 'Tẩu', onyomi: 'ソウ', kunyomi: 'はし', exampleVocab: '競走 (kyousou - race)', type: 'kanji' },
  { id: 'kn88', char: '会', romaji: 'au', meaning: 'To meet', sinoVietnamese: 'Hội', onyomi: 'カイ', kunyomi: 'あ', exampleVocab: '会社 (kaisha - company)', type: 'kanji' },
  { id: 'kn89', char: '名', romaji: 'na', meaning: 'Name', sinoVietnamese: 'Danh', onyomi: 'メイ', kunyomi: 'な', exampleVocab: '有名 (yuumei - famous)', type: 'kanji' },
  { id: 'kn90', char: '白', romaji: 'shiro', meaning: 'White', sinoVietnamese: 'Bạch', onyomi: 'ハク', kunyomi: 'しろ', exampleVocab: '白鳥 (hakuchou - swan)', type: 'kanji' },
  { id: 'kn91', char: '口', romaji: 'kuchi', meaning: 'Mouth', sinoVietnamese: 'Khẩu', onyomi: 'コウ', kunyomi: 'くち', exampleVocab: '口調 (kuchou - tone)', type: 'kanji' },
  { id: 'kn92', char: '目', romaji: 'me', meaning: 'Eye', sinoVietnamese: 'Mục', onyomi: 'モク', kunyomi: 'め', exampleVocab: '目次 (mokuji - index)', type: 'kanji' },
  { id: 'kn93', char: '耳', romaji: 'mimi', meaning: 'Ear', sinoVietnamese: 'Nhĩ', onyomi: 'ジ', kunyomi: 'みみ', exampleVocab: '耳鼻科 (jibika - otolaryngology)', type: 'kanji' },
  { id: 'kn94', char: '手', romaji: 'te', meaning: 'Hand', sinoVietnamese: 'Thủ', onyomi: 'シュ', kunyomi: 'て', exampleVocab: '手紙 (tegami - letter)', type: 'kanji' },
  { id: 'kn95', char: '足', romaji: 'ashi', meaning: 'Foot / Sufficient', sinoVietnamese: 'Túc', onyomi: 'ソク', kunyomi: 'あし', exampleVocab: '遠足 (ensoku - excursion)', type: 'kanji' },
  { id: 'kn96', char: '万', romaji: 'man', meaning: 'Ten Thousand', sinoVietnamese: 'Vạn', onyomi: 'マン', kunyomi: 'よろず', exampleVocab: '万歳 (banzai - cheers)', type: 'kanji' },
  { id: 'kn97', char: '半', romaji: 'han', meaning: 'Half', sinoVietnamese: 'Bán', onyomi: 'ハン', kunyomi: 'なか', exampleVocab: '半分 (hanbun - half)', type: 'kanji' },
  { id: 'kn98', char: '夕', romaji: 'yuu', meaning: 'Evening', sinoVietnamese: 'Tịch', onyomi: 'セキ', kunyomi: 'ゆう', exampleVocab: '夕方 (yuugata - evening)', type: 'kanji' },
  { id: 'kn99', char: '外', romaji: 'soto', meaning: 'Outside', sinoVietnamese: 'Ngoại', onyomi: 'ガイ', kunyomi: 'そと', exampleVocab: '外国 (gaikoku - foreign country)', type: 'kanji' },
  { id: 'kn100', char: '多', romaji: 'ooi', meaning: 'Many', sinoVietnamese: 'Đa', onyomi: 'タ', kunyomi: 'おお', exampleVocab: '多分 (tabun - probably)', type: 'kanji' },
  { id: 'kn101', char: '広', romaji: 'hiroi', meaning: 'Wide / Spacious', sinoVietnamese: 'Quảng', onyomi: 'コウ', kunyomi: 'ひろ', exampleVocab: '広告 (koukoku - advertisement)', type: 'kanji' },
  { id: 'kn102', char: '冬', romaji: 'fuyu', meaning: 'Winter', sinoVietnamese: 'Đông', onyomi: 'トウ', kunyomi: 'ふゆ', exampleVocab: '冬休み (fuyuyasumi - winter vacation)', type: 'kanji' },
  { id: 'kn103', char: '夏', romaji: 'natsu', meaning: 'Summer', sinoVietnamese: 'Hạ', onyomi: 'カ', kunyomi: 'naつ', exampleVocab: '夏休み (natsuyasumi - summer vacation)', type: 'kanji' },
  { id: 'kn104', char: '秋', romaji: 'aki', meaning: 'Autumn', sinoVietnamese: 'Thu', onyomi: 'シュウ', kunyomi: 'あき', exampleVocab: '秋分 (shuubun - autumn equinox)', type: 'kanji' },
  { id: 'kn105', char: '春', romaji: 'haru', meaning: 'Spring', sinoVietnamese: 'Xuân', onyomi: 'シュン', kunyomi: 'はる', exampleVocab: '春分 (shunbun - spring equinox)', type: 'kanji' },
  { id: 'kn106', char: '東', romaji: 'higashi', meaning: 'East', sinoVietnamese: 'Đông', onyomi: 'トウ', kunyomi: 'ひがし', exampleVocab: '東京 (toukyou - Tokyo)', type: 'kanji' },
  { id: 'kn107', char: '西', romaji: 'nishi', meaning: 'West', sinoVietnamese: 'Tây', onyomi: 'セイ', kunyomi: 'にし', exampleVocab: '北西 (hokusei - northwest)', type: 'kanji' },
  { id: 'kn108', char: '南', romaji: 'minami', meaning: 'South', sinoVietnamese: 'Nam', onyomi: 'ナン', kunyomi: 'みなみ', exampleVocab: '南国 (nangoku - southern country)', type: 'kanji' },
  { id: 'kn109', char: '北', romaji: 'kita', meaning: 'North', sinoVietnamese: 'Bắc', onyomi: 'ホク', kunyomi: 'kita', exampleVocab: '北海道 (hokkaidou - Hokkaido)', type: 'kanji' },
  { id: 'kn110', char: '道', romaji: 'michi', meaning: 'Road / Way', sinoVietnamese: 'Đạo', onyomi: 'ドウ', kunyomi: 'michi', exampleVocab: '書道 (shodou - calligraphy)', type: 'kanji' },
];

export const VOCABULARY_N5: JapaneseChar[] = [
  { id: 'v1', char: '先生', romaji: 'sensei', meaning: 'Teacher', type: 'vocabulary' },
  { id: 'v2', char: '学生', romaji: 'gakusei', meaning: 'Student', type: 'vocabulary' },
  { id: 'v3', char: '日本', romaji: 'nihon', meaning: 'Japan', type: 'vocabulary' },
  { id: 'v4', char: '学校', romaji: 'gakkou', meaning: 'School', type: 'vocabulary' },
  { id: 'v5', char: '猫', romaji: 'neko', meaning: 'Cat', type: 'vocabulary' },
];

export const GRAMMAR_N5: GrammarPoint[] = [
  {
    id: 'g1',
    title: 'Desu (State of Being)',
    structure: 'Noun + です',
    explanation: '"Desu" is used to state that something is something else. It functions like "is", "am", or "are" in English.',
    example_jp: '私は学生です。',
    example_en: 'I am a student.'
  },
  {
    id: 'g2',
    title: 'Wa (Topic Marker)',
    structure: 'Noun + は',
    explanation: 'The particle "Wa" identifies the topic of the sentence. Pronounced "ha", but read as "wa".',
    example_jp: 'これは本です。',
    example_en: 'This is a book.'
  }
];
